from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List
import os
from database import get_db
from models import User, HabitLog

router = APIRouter(prefix="/tasks", tags=["tasks"])

# The 10 categories with default tasks
# When Gemini is working these get generated by AI
# For now they're hardcoded but smart defaults


DEFAULT_TASKS = {
    "sleep": [
        "Take a photo of your bed made in the morning",
        "Take a photo of your phone on do not disturb before 11pm",
        "Take a photo of your sleep tracker or alarm set for 8 hours"
    ],
    "physique": [
        "Take a photo of yourself at the gym or working out",
        "Take a photo of your completed workout logged in an app",
        "Take a photo of yourself on a walk or run outside"
    ],
    "water": [
        "Take a photo of your water bottle filled up",
        "Take a photo of 8 empty glasses or a full water jug",
        "Take a photo of your water intake tracker"
    ],
    "nutrition": [
        "Take a photo of your healthy meal",
        "Take a photo of your plate with vegetables on it",
        "Take a photo of your healthy breakfast"
    ],
    "mood": [
        "Take a photo of your journal with 3 things you are grateful for written down",
        "Take a photo of yourself smiling",
        "Take a photo of something that made you happy today"
    ],
    "school": [
        "Take a photo of your completed homework",
        "Take a photo of your notes from studying",
        "Take a photo of your finished assignment"
    ],
    "work": [
        "Take a photo of your completed to do list",
        "Take a photo of your clean and organised desk",
        "Take a photo of your cleared email inbox"
    ],
    "mindfulness": [
        "Take a photo of your meditation app showing a completed session",
        "Take a photo of yourself outside in nature or fresh air",
        "Take a photo of your journal after writing"
    ],
    "screentime": [
        "Take a photo of your screen time showing reduced usage",
        "Take a photo of your phone face down during a meal",
        "Take a photo of your phone showing app limits enabled"
    ],
    "social": [
        "Take a photo of a meal or activity with friends or family",
        "Take a photo of a handwritten note or card you made for someone",
        "Take a photo of yourself and a friend or family member together"
    ]
}

import random

class TaskGenerateRequest(BaseModel):
    categories: List[str]

class TaskCompleteRequest(BaseModel):
    category: str
    task: str

def get_current_user(token: str, db: Session):
    from jose import JWTError, jwt
    try:
        payload = jwt.decode(token, os.getenv("SECRET_KEY"), algorithms=["HS256"])
        user_id = int(payload.get("sub"))
        user = db.query(User).filter(User.id == user_id).first()
        if not user:
            raise HTTPException(status_code=401, detail="User not found")
        return user
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid token")

# Generate daily tasks for user's chosen categories
@router.post("/generate")
def generate_tasks(
    request: TaskGenerateRequest,
    token: str,
    db: Session = Depends(get_db)
):
    user = get_current_user(token, db)
    
    # Validate categories
    valid_categories = list(DEFAULT_TASKS.keys())
    invalid = [c for c in request.categories if c not in valid_categories]
    if invalid:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid categories: {invalid}. Must be one of {valid_categories}"
        )
    
    # Generate one task per category
    tasks = {}
    for category in request.categories:
        tasks[category] = random.choice(DEFAULT_TASKS[category])
    
    return {
        "user_id": user.id,
        "tasks": tasks,
        "total": len(tasks)
    }

# Mark task as complete — photo verification happens here later
@router.post("/complete")
def complete_task(
    request: TaskCompleteRequest,
    token: str,
    db: Session = Depends(get_db)
):
    user = get_current_user(token, db)
    
    # Save completed task as habit log
    habit_log = HabitLog(
        user_id=user.id,
        habit_category=request.category,
        habit_description=request.task,
        health_score=0.75  # Placeholder until Gemini vision is added
    )
    db.add(habit_log)
    db.commit()
    
    return {
        "message": "Task completed successfully",
        "category": request.category,
        "task": request.task,
        "score": 0.75,
        "feedback": "Great job completing your task!"
    }

# Get all available categories and sample tasks
@router.get("/categories")
def get_categories():
    return {
        "categories": list(DEFAULT_TASKS.keys()),
        "total": len(DEFAULT_TASKS)
    }